### ISSUE TITLE
Setting up remote environment

### ISSUE THREAD

**Issue by pbrady** [xangma/vscode_remote_slurm#5]
Thanks for putting this script together.  I can successfully run vscode on a compute node in our cluster!  Any ideas on how to setup the proper environment for the remote server?

For example, I used to have the following line in my `.ssh/config`:
```console
RemoteCommand source ~/setup-spack.sh && ml clang cuda/11.7.0 openmpi/4.1.4-gcc_12.1.0 cmake git && spack env activate my-custom-spackenv; bash
```
This would setup all the correct environment variables so that VScode could find all right files (but only the login-node which is not great).  I've tried to combine this with your `salloc` RemoteCommand but haven't figured out the right incantation.  For example, this does not work:
```console
RemoteCommand source ~/setup-spack.sh && ml clang openmpi/4.1.4-gcc_12.1.0 git && spack env activate my-custom-spackenv &&  salloc --no-shell -N 1 -V -p skylake-gold -J vscode --time=04:00:00
```

Any ideas?  Modifying my `.bashrc` is a non-starter

**Comment by davide-q** [comment]
You could write all that spack and module setup into its one file, then you have to make sure that such a file is sourced before VSCode runs.

I am not sure how to do that, since VSCode makes it really hard (I have yet to succeed making VSCode work on a compute node: I can connect but it fails to work, but I digress)

One way to do that, assuming that what would run on the compute node is something like `~/.vscode-server/whatever` is to rename that to something like `~/.vscode-server/whatever.for_real` and create a new `~/.vscode-server/whatever` text file containing something like

```bash
#!/bin/bash
source ~/setup-spack.sh
ml clang openmpi/4.1.4-gcc_12.1.0 git
spack env activate my-custom-spackenv
~/.vscode-server/whatever.for_real
```

hope this helps

**Comment by davide-q** [comment]
PS: one way to check how VSCode is running, would be to use a shell access from the login node, running something like `srun --job-id NNNN --pty bash` (assuming it's enabled on your cluster, if not ask your sysadmins for help) and then running `ps aux | grep $USER)

You will see something like what I called `~/.vscode-server/whatever` in my previous comment

**Comment by pbrady** [comment]
Thanks for the input!  I ended up modifying the `ssh_wrapper` to make the text of `RemoteCommand` prior to `salloc` part of the `stdin_commands`.  I'm still having some issues with clangd paths but I haven't had the patience to figure out if my modifications are causing it or something else on the remote system. 

This is a really helpful tool.  Thanks again.
